// ============================================================================
// COMPLIANCE-PROOF WITNESS IMPLEMENTATIONS
// ============================================================================
//
// Off-chain computation for the compliance attestation contract.
//
// IMPORTANT: Function names and signatures MUST match the generated types
// in managed/compliance-proof/contract/index.d.ts exactly:
//
//   Witnesses<PS> = {
//     getCurrentTimestamp(ctx): [PS, bigint]
//     computeUniqueAttestationHash(ctx, caseIdentifier: bigint,
//       stepOrPhaseHash: bigint, attestationTimestamp: bigint): [PS, Uint8Array]
//   }
//
// NOTE: ownPublicKey() is NOT a witness — it's a built-in handled by runtime.
// ============================================================================

import { type WitnessContext } from "@midnight-ntwrk/compact-runtime";
import type { Ledger } from "../managed/compliance-proof/contract/index.js";

// --- Private State Type ---

export type CompliancePrivateState = {
  // Local cache of attestation hashes generated by this user (hex strings)
  generatedAttestationHashes: string[];
};

// --- Private State Factory ---

export const createCompliancePrivateState = (): CompliancePrivateState => ({
  generatedAttestationHashes: [],
});

// --- Deterministic Hash Utility ---
// Produces a deterministic Uint8Array (32 bytes) from bigint inputs.
// Used for attestation hash computation.

function deterministicHashToBytes32(...inputs: bigint[]): Uint8Array {
  // Convert each bigint to 32-byte big-endian, then mix
  const totalLength = inputs.length * 32;
  const combined = new Uint8Array(totalLength);
  for (let i = 0; i < inputs.length; i++) {
    const hexString = inputs[i].toString(16).padStart(64, '0');
    for (let j = 0; j < 32; j++) {
      combined[i * 32 + j] = parseInt(hexString.slice(j * 2, j * 2 + 2), 16);
    }
  }

  // FNV-1a-inspired mixing to produce 32 output bytes
  const result = new Uint8Array(32);
  let hashHigh = 0xcbf29ce484222325n;
  let hashLow = 0x100000001b3n;
  const prime = 0x01000000000000000000013bn;
  const mask64 = (1n << 64n) - 1n;

  for (let i = 0; i < combined.length; i++) {
    hashHigh ^= BigInt(combined[i]);
    hashHigh = (hashHigh * prime) & mask64;
    hashLow ^= BigInt(combined[i]) ^ BigInt(i);
    hashLow = (hashLow * prime) & mask64;
  }

  // Fill result bytes from the two accumulators
  for (let i = 0; i < 8; i++) {
    result[i] = Number((hashHigh >> BigInt(i * 8)) & 0xffn);
    result[i + 8] = Number((hashLow >> BigInt(i * 8)) & 0xffn);
    result[i + 16] = Number(((hashHigh ^ hashLow) >> BigInt(i * 8)) & 0xffn);
    result[i + 24] = Number(((hashHigh + hashLow) >> BigInt(i * 8)) & 0xffn);
  }

  return result;
}

// --- Witness Implementations ---

/**
 * getCurrentTimestamp
 *
 * Returns the current Unix timestamp (seconds since epoch).
 * Used for recording when attestations are created.
 *
 * @returns [unchangedPrivateState, currentTimestamp]
 */
export const getCurrentTimestamp = (
  context: WitnessContext<Ledger, CompliancePrivateState>,
): [CompliancePrivateState, bigint] => {
  const timestamp = BigInt(Math.floor(Date.now() / 1000));
  return [context.privateState, timestamp];
};

/**
 * computeUniqueAttestationHash
 *
 * Computes a unique attestation hash from case ID, step/phase hash, and timestamp.
 * This becomes the immutable proof identifier stored on the public ledger.
 * Courts and auditors use this hash to verify compliance without seeing case details.
 *
 * @param context - WitnessContext with ledger and private state
 * @param caseIdentifier_0 - The case this attestation belongs to (Field / bigint)
 * @param stepOrPhaseHash_0 - Which step or phase is being attested (Field / bigint)
 * @param attestationTimestamp_0 - When the attestation was created (Field / bigint)
 * @returns [updatedPrivateState, attestationHash as Bytes<32>]
 */
export const computeUniqueAttestationHash = (
  context: WitnessContext<Ledger, CompliancePrivateState>,
  caseIdentifier_0: bigint,
  stepOrPhaseHash_0: bigint,
  attestationTimestamp_0: bigint,
): [CompliancePrivateState, Uint8Array] => {
  const attestationHash = deterministicHashToBytes32(
    caseIdentifier_0,
    stepOrPhaseHash_0,
    attestationTimestamp_0,
  );

  // Track this attestation in private state
  const hashHex = Array.from(attestationHash)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');

  const updatedState: CompliancePrivateState = {
    ...context.privateState,
    generatedAttestationHashes: [
      ...context.privateState.generatedAttestationHashes,
      hashHex,
    ],
  };

  return [updatedState, attestationHash];
};

// --- Witness Map (for contract binding) ---
// Names MUST match generated Witnesses<PS> type exactly.

export const complianceWitnesses = {
  getCurrentTimestamp,
  computeUniqueAttestationHash,
};
